<?xml version="1.0"?>
<!-- CORBA XML document created by XMLSerializer2 1.6 at 2013-08-01 06:21:15 UTC, from SL 2.77-r27212 built 2012-06-14 12:14:32 UTC -->
<!DOCTYPE any [
<!ELEMENT any (any|typecode|sequence|array|struct|union|exception|string|objectref|enum|boolean|char|octet|short|ushort|long|ulong|float|double)?>
<!ATTLIST any name NMTOKEN #IMPLIED type_id CDATA #IMPLIED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED version CDATA #IMPLIED>
<!ELEMENT typecode (any|typecode|sequence|array|struct|union|exception|string|objectref|enum|boolean|char|octet|short|ushort|long|ulong|float|double)?>
<!ATTLIST typecode name NMTOKEN #IMPLIED type_id CDATA #IMPLIED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT sequence ((any|typecode|sequence|array|struct|union|exception|string|objectref)+|(enum|boolean|char|octet|short|ushort|long|ulong|float|double))?>
<!ATTLIST sequence name NMTOKEN #IMPLIED type_id CDATA #IMPLIED type_name NMTOKEN #IMPLIED length NMTOKEN #REQUIRED bound NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT array ((any|typecode|sequence|array|struct|union|exception|string|objectref)+|(enum|boolean|char|octet|short|ushort|long|ulong|float|double))?>
<!ATTLIST array name NMTOKEN #IMPLIED type_id CDATA #IMPLIED type_name NMTOKEN #IMPLIED length NMTOKEN #REQUIRED label NMTOKEN #IMPLIED>
<!ELEMENT struct (any|typecode|sequence|array|struct|union|exception|string|objectref|enum|boolean|char|octet|short|ushort|long|ulong|float|double)*>
<!ATTLIST struct name NMTOKEN #IMPLIED type_id CDATA #REQUIRED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT union (any|typecode|sequence|array|struct|union|exception|string|objectref|enum|boolean|char|octet|short|ushort|long|ulong|float|double)*>
<!ATTLIST union name NMTOKEN #IMPLIED type_id CDATA #REQUIRED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT exception (any|typecode|sequence|array|struct|union|exception|string|objectref|enum|boolean|char|octet|short|ushort|long|ulong|float|double)*>
<!ATTLIST exception name NMTOKEN #IMPLIED type_id CDATA #REQUIRED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT string (#PCDATA)>
<!ATTLIST string name NMTOKEN #IMPLIED type_id CDATA #IMPLIED type_name NMTOKEN #IMPLIED bound NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT objectref (#PCDATA)>
<!ATTLIST objectref name NMTOKEN #IMPLIED type_id CDATA #REQUIRED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT enum (#PCDATA)>
<!ATTLIST enum name NMTOKEN #IMPLIED type_id CDATA #REQUIRED type_name NMTOKEN #IMPLIED values NMTOKENS #REQUIRED label NMTOKEN #IMPLIED>
<!ELEMENT boolean (#PCDATA)>
<!ATTLIST boolean name NMTOKEN #IMPLIED type_id CDATA #IMPLIED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT char (#PCDATA)>
<!ATTLIST char name NMTOKEN #IMPLIED type_id CDATA #IMPLIED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT octet (#PCDATA)>
<!ATTLIST octet name NMTOKEN #IMPLIED type_id CDATA #IMPLIED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT short (#PCDATA)>
<!ATTLIST short name NMTOKEN #IMPLIED type_id CDATA #IMPLIED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT ushort (#PCDATA)>
<!ATTLIST ushort name NMTOKEN #IMPLIED type_id CDATA #IMPLIED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT long (#PCDATA)>
<!ATTLIST long name NMTOKEN #IMPLIED type_id CDATA #IMPLIED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT ulong (#PCDATA)>
<!ATTLIST ulong name NMTOKEN #IMPLIED type_id CDATA #IMPLIED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT float (#PCDATA)>
<!ATTLIST float name NMTOKEN #IMPLIED type_id CDATA #IMPLIED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT double (#PCDATA)>
<!ATTLIST double name NMTOKEN #IMPLIED type_id CDATA #IMPLIED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
]>
<any version="1.6">
<sequence length="1" type_id="IDL:specs.de/Serializer/RegionGroupSeq:1.0" type_name="RegionGroupSeq">
<struct type_id="IDL:specs.de/Serializer/RegionGroup:1.0" type_name="RegionGroup">
<string name="name">05 Gold nach MCD kalib 2100V Det</string>
<sequence name="regions" length="2" type_id="IDL:specs.de/Serializer/RegionDataSeq:1.0" type_name="RegionDataSeq">
<struct type_id="IDL:specs.de/Serializer/RegionData:1.0" type_name="RegionData">
<string name="name">Au4f 10pass MedArea</string>
<struct name="region" type_id="IDL:specs.de/SurfaceAnalysis/RegionDef:1.0" type_name="RegionDef">
<string name="analysis_method">XPS</string>
<string name="analyzer_lens">MediumArea:1.5kV</string>
<string name="detector_dataset">phoibos150-DLD1D_20130731</string>
<string name="detector_dataset_directory">C:\Programme\SPECS\SpecsLab2\database\datasetCalib1d</string>
<string name="analyzer_slit">5:7x20\2:open</string>
<struct name="scan_mode" type_id="IDL:specs.de/SurfaceAnalysis/ScanMode:1.0" type_name="ScanMode">
<string name="name">Snapshot (FAT)</string>
<ulong name="flags" type_id="IDL:specs.de/SurfaceAnalysis/ScanModeFlags:1.0" type_name="ScanModeFlags">258</ulong>
</struct>
<ulong name="num_scans">40</ulong>
<ulong name="curves_per_scan">1</ulong>
<ulong name="values_per_curve">8</ulong>
<double name="dwell_time">0.5</double>
<double name="scan_delta">1.99523535353535</double>
<double name="excitation_energy">1253.6</double>
<double name="kinetic_energy">1161.10983</double>
<double name="kinetic_energy_base">0</double>
<double name="pass_energy">10</double>
<double name="bias_voltage">80</double>
<double name="detector_voltage">2100</double>
<double name="effective_workfunction">4.387</double>
</struct>
<ulong name="mcd_head">0</ulong>
<ulong name="mcd_tail">0</ulong>
<struct name="analyzer_info" type_id="IDL:specs.de/SurfaceAnalysis/AnalyzerInfo:1.0" type_name="AnalyzerInfo">
<string name="name">PHOIBOS HSA3500 DLSEGD 150 R6[HWType 30:15] DLSEGD</string>
<sequence name="detectors" length="100" type_id="IDL:specs.de/SurfaceAnalysis/DetectorSeq:1.0" type_name="DetectorSeq">
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">-17.424</double>
<double name="shift">-0.115239</double>
<double name="gain">3.05731</double>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">-17.072</double>
<double name="shift">-0.113243</double>
<double name="gain">1.10853</double>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">-16.72</double>
<double name="shift">-0.111248</double>
<double name="gain">0.900584</double>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">-16.368</double>
<double name="shift">-0.109253</double>
<double name="gain">1.02714</double>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">-16.016</double>
<double name="shift">-0.107258</double>
<double name="gain">1.22084</double>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">-15.664</double>
<double name="shift">-0.105262</double>
<double name="gain">1.08888</double>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">-15.312</double>
<double name="shift">-0.103267</double>
<double name="gain">0.988032</double>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">-14.96</double>
<double name="shift">-0.101272</double>
<double name="gain">1.17469</double>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">-14.608</double>
<double name="shift">-0.0992767</double>
<double name="gain">0.996832</double>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">-14.256</double>
<double name="shift">-0.0972814</double>
<double name="gain">1.20437</double>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">-13.904</double>
<double name="shift">-0.0952862</double>
<double name="gain">1.14666</double>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">-13.552</double>
<double name="shift">-0.093291</double>
<double name="gain">1.1011</double>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">-13.2</double>
<double name="shift">-0.0912957</double>
<double name="gain">1.09965</double>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">-12.848</double>
<double name="shift">-0.0893005</double>
<double name="gain">1.11245</double>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">-12.496</double>
<double name="shift">-0.0873053</double>
<double name="gain">1.17186</double>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">-12.144</double>
<double name="shift">-0.0853101</double>
<double name="gain">1.1391</double>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">-11.792</double>
<double name="shift">-0.0833148</double>
<double name="gain">1.12262</double>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">-11.44</double>
<double name="shift">-0.0813196</double>
<double name="gain">1.15926</double>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">-11.088</double>
<double name="shift">-0.0793244</double>
<double name="gain">1.00108</double>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">-10.736</double>
<double name="shift">-0.0773291</double>
<double name="gain">0.982411000000001</double>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">-10.384</double>
<double name="shift">-0.0753339</double>
<double name="gain">1.07424</double>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">-10.032</double>
<double name="shift">-0.0733387</double>
<double name="gain">0.985486</double>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">-9.68</double>
<double name="shift">-0.0713434</double>
<double name="gain">0.950993</double>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">-9.328</double>
<double name="shift">-0.0693482</double>
<double name="gain">0.889737</double>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">-8.976</double>
<double name="shift">-0.067353</double>
<double name="gain">1.0049</double>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">-8.624</double>
<double name="shift">-0.0653578</double>
<double name="gain">0.936646</double>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">-8.272</double>
<double name="shift">-0.0633625</double>
<double name="gain">0.910106</double>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">-7.92</double>
<double name="shift">-0.0613673</double>
<double name="gain">0.944622</double>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">-7.568</double>
<double name="shift">-0.0593721</double>
<double name="gain">0.902774</double>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">-7.216</double>
<double name="shift">-0.0573768</double>
<double name="gain">0.891964</double>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">-6.864</double>
<double name="shift">-0.0553816</double>
<double name="gain">0.895521</double>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">-6.512</double>
<double name="shift">-0.0533864</double>
<double name="gain">0.730286</double>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">-6.16</double>
<double name="shift">-0.0513911</double>
<double name="gain">0.843479</double>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">-5.808</double>
<double name="shift">-0.0493959</double>
<double name="gain">0.741253</double>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">-5.456</double>
<double name="shift">-0.0474007</double>
<double name="gain">0.781949000000001</double>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">-5.104</double>
<double name="shift">-0.0454055</double>
<double name="gain">1.00198</double>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">-4.752</double>
<double name="shift">-0.0434102</double>
<double name="gain">0.725334</double>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">-4.4</double>
<double name="shift">-0.041415</double>
<double name="gain">0.805217</double>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">-4.048</double>
<double name="shift">-0.0394198</double>
<double name="gain">0.717091</double>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">-3.696</double>
<double name="shift">-0.0374245</double>
<double name="gain">0.814882</double>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">-3.344</double>
<double name="shift">-0.0354293</double>
<double name="gain">0.718236</double>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">-2.992</double>
<double name="shift">-0.0334341</double>
<double name="gain">0.778149</double>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">-2.64</double>
<double name="shift">-0.0314388</double>
<double name="gain">0.742075</double>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">-2.288</double>
<double name="shift">-0.0294436</double>
<double name="gain">0.715278</double>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">-1.936</double>
<double name="shift">-0.0274484</double>
<double name="gain">0.846841</double>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">-1.584</double>
<double name="shift">-0.0254532</double>
<double name="gain">0.868044</double>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">-1.232</double>
<double name="shift">-0.0234579</double>
<double name="gain">0.905158</double>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">-0.88</double>
<double name="shift">-0.0214627</double>
<double name="gain">0.805944</double>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">-0.528</double>
<double name="shift">-0.0194675</double>
<double name="gain">0.859894</double>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">-0.176</double>
<double name="shift">-0.0174722</double>
<double name="gain">0.872477</double>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">0.176</double>
<double name="shift">-0.015477</double>
<double name="gain">0.798658</double>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">0.528</double>
<double name="shift">-0.0134818</double>
<double name="gain">0.843006</double>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">0.88</double>
<double name="shift">-0.0114865</double>
<double name="gain">0.784895</double>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">1.232</double>
<double name="shift">-0.00949132</double>
<double name="gain">0.921855</double>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">1.584</double>
<double name="shift">-0.00749609</double>
<double name="gain">0.900109</double>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">1.936</double>
<double name="shift">-0.00550086</double>
<double name="gain">0.8606</double>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">2.288</double>
<double name="shift">-0.00350563</double>
<double name="gain">0.967462</double>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">2.64</double>
<double name="shift">-0.0015104</double>
<double name="gain">0.872104</double>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">2.992</double>
<double name="shift">0.000484833</double>
<double name="gain">0.830477</double>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">3.344</double>
<double name="shift">0.00248006</double>
<double name="gain">0.883987</double>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">3.696</double>
<double name="shift">0.00447529</double>
<double name="gain">0.939526</double>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">4.048</double>
<double name="shift">0.00647052</double>
<double name="gain">1.00901</double>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">4.4</double>
<double name="shift">0.00846574999999999</double>
<double name="gain">0.885112000000001</double>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">4.752</double>
<double name="shift">0.010461</double>
<double name="gain">0.772843</double>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">5.104</double>
<double name="shift">0.0124562</double>
<double name="gain">0.992246</double>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">5.456</double>
<double name="shift">0.0144514</double>
<double name="gain">0.818076</double>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">5.808</double>
<double name="shift">0.0164467</double>
<double name="gain">0.870481</double>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">6.16</double>
<double name="shift">0.0184419</double>
<double name="gain">0.878847</double>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">6.512</double>
<double name="shift">0.0204371</double>
<double name="gain">0.794222</double>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">6.864</double>
<double name="shift">0.0224324</double>
<double name="gain">0.89111</double>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">7.216</double>
<double name="shift">0.0244276</double>
<double name="gain">0.889836</double>